name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - ci-cd-pipeline
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    
    - name: Run tests with coverage
      run: |
        go test -v -coverprofile=coverage.out -covermode=atomic -coverpkg=./... ./...
        go tool cover -html=coverage.out -o coverage.html
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        files: coverage.out
        flags: unittests
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.html
        retention-days: 1

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    
    - name: Build
      run: |
        GOOS=$(echo ${{ matrix.os }} | cut -d'-' -f1)
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          # Build for both Intel and Apple Silicon
          GOARCH=amd64 OUTPUT=aicraft-cli-macos-intel-alpha go build -o aicraft-cli-macos-intel-alpha .
          GOARCH=arm64 OUTPUT=aicraft-cli-macos-arm64-alpha go build -o aicraft-cli-macos-arm64-alpha .
          echo "OUTPUT_FILES=aicraft-cli-macos-intel-alpha aicraft-cli-macos-arm64-alpha" >> $GITHUB_ENV
        else
          GOARCH=amd64
          OUTPUT=aicraft-cli-${{ matrix.os }}-alpha
          go build -o $OUTPUT .
          echo "OUTPUT_FILES=$OUTPUT" >> $GITHUB_ENV
        fi
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aicraft-cli-${{ matrix.os }}-alpha
        path: |
          ${{ env.OUTPUT_FILES }}
        retention-days: 5

  release:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        pattern: aicraft-cli-*-alpha
        merge-multiple: true
    
    - name: Create release and upload assets
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: alpha-${{ github.sha }}
        name: Alpha Release ${{ github.sha }}
        prerelease: true
        files: |
          artifacts/aicraft-cli-ubuntu-latest-alpha
          artifacts/aicraft-cli-windows-latest-alpha
          artifacts/aicraft-cli-macos-latest-alpha